export const apiRoutes = {
  changeSettings: "/users/settings",
  changeUserNickname: "/users/nickname",
  diary: "/diaries",
  diaryTempSave: "/diaries/temp",
  diaryTempCancel: "/diaries/cancel",
  likeDiary: "/diaries/like",
  searchDiary: "/diaries/search",
  mainDiary: "diaries/main",
  images: "/images",
  login: "/auth/kakao/login",
  refresh: "/auth/refresh",
  logout: "/auth/logout",
  auth: "/auth",
};
